"""
Core data models for the Multi-Agent Debate framework.
All models use Pydantic for validation and serialization.
"""
from __future__ import annotations
from enum import Enum
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime
import uuid


class ConflictType(str, Enum):
    """Types of conflicts that can be detected between evidence."""
    FACTUAL = "factual"
    TEMPORAL = "temporal"
    VERSION = "version"
    CONTEXTUAL = "contextual"
    SOURCE = "source"
    UNKNOWN = "unknown"


class NLILabel(str, Enum):
    """NLI relationship labels."""
    ENTAILMENT = "entailment"
    CONTRADICTION = "contradiction"
    NEUTRAL = "neutral"


class Source(BaseModel):
    """Source information for evidence."""
    url: str
    title: str
    snippet: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
    retrieved_at: datetime = Field(default_factory=datetime.now)
    credibility_score: Optional[float] = None


class Claim(BaseModel):
    """A single claim extracted from evidence."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    text: str
    source: Source
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class Evidence(BaseModel):
    """Evidence retrieved by an agent for a query."""
    agent_id: str
    query: str
    answer: str
    claims: List[Claim] = Field(default_factory=list)
    sources: List[Source] = Field(default_factory=list)
    retrieved_text: str = ""
    metadata: Dict[str, Any] = Field(default_factory=dict)
    retrieved_at: datetime = Field(default_factory=datetime.now)


class EvidenceComparison(BaseModel):
    """Result of comparing evidence from two agents."""
    agent_a_id: str
    agent_b_id: str
    claim_pairs: List[Dict[str, Any]] = Field(default_factory=list)
    nli_results: List[Dict[str, Any]] = Field(default_factory=list)
    has_disagreement: bool = False
    contradiction_score: float = 0.0
    entailment_score: float = 0.0
    neutral_score: float = 0.0
    conflicts: List[Dict[str, Any]] = Field(default_factory=list)
    compared_at: datetime = Field(default_factory=datetime.now)


class Conflict(BaseModel):
    """A detected conflict between evidence."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    type: ConflictType
    confidence: float = Field(ge=0.0, le=1.0)
    explanation: str
    claim_a: Claim
    claim_b: Claim
    metadata: Dict[str, Any] = Field(default_factory=dict)
    detected_at: datetime = Field(default_factory=datetime.now)


class DebateArgument(BaseModel):
    """An argument made during debate."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    round_number: int
    role: str  # "proposer", "critic", "reviser"
    agent_id: str
    content: str
    evidence_refs: List[str] = Field(default_factory=list)
    conflict_type: Optional[ConflictType] = None
    strategy_used: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.now)


class DebateRound(BaseModel):
    """A single round of debate."""
    round_number: int
    proposer_argument: Optional[DebateArgument] = None
    critic_arguments: List[DebateArgument] = Field(default_factory=list)
    reviser_argument: Optional[DebateArgument] = None
    started_at: datetime = Field(default_factory=datetime.now)
    completed_at: Optional[datetime] = None


class JudgeResult(BaseModel):
    """Result from the judge evaluating debate outcomes."""
    winner: str  # candidate identifier
    reason: str
    evidence_score: float = Field(ge=0.0, le=1.0)
    reasoning_score: float = Field(ge=0.0, le=1.0)
    source_score: float = Field(ge=0.0, le=1.0)
    confidence: float = Field(ge=0.0, le=1.0)
    scores: Dict[str, float] = Field(default_factory=dict)
    evaluated_at: datetime = Field(default_factory=datetime.now)


class FinalAnswer(BaseModel):
    """Final answer generated by the system."""
    query: str
    answer: str
    reasoning: str
    evidence: List[Evidence] = Field(default_factory=list)
    sources: List[Source] = Field(default_factory=list)
    debate_triggered: bool = False
    conflict: Optional[Conflict] = None
    debate_rounds: List[DebateRound] = Field(default_factory=list)
    judge_result: Optional[JudgeResult] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    generated_at: datetime = Field(default_factory=datetime.now)


class ExecutionTrace(BaseModel):
    """Complete execution trace for logging and evaluation."""
    query: str
    trace_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    router_result: Dict[str, Any] = Field(default_factory=dict)
    agents: List[Evidence] = Field(default_factory=list)
    evidence_comparison: Optional[EvidenceComparison] = None
    disagreement_detected: bool = False
    contradiction_score: float = 0.0
    debate_triggered: bool = False
    conflict: Optional[Conflict] = None
    debate_rounds: List[DebateRound] = Field(default_factory=list)
    judge_result: Optional[JudgeResult] = None
    final_answer: Optional[FinalAnswer] = None
    metrics: Dict[str, Any] = Field(default_factory=dict)
    started_at: datetime = Field(default_factory=datetime.now)
    completed_at: Optional[datetime] = None
    error: Optional[str] = None